 decoration {
    rounding = 12       # 圆角大小
    blur {
    #enable = yes
    size = 5       # 模糊半径
    passes = 1     # 模糊过滤次数
    new_optimizations = on     # 模糊优化，通常保持打开
    }
    shadow { 
    #enable = yes  
    range = 4    # 投影大小
    render_power = 3     # 投影强度，不过我不太明白这是什么意思
    color = rgba(1a1a1aee)     # 投影颜色
    }
    active_opacity = 0.7
    inactive_opacity = 0.7
    fullscreen_opacity = 0.7
   }
