
    windowrule = opaque,noblur, onworkspace:9
    windowrulev2 = float, title:QQ
    windowrulev2 = noblur,class:^(osu!)$,title:^(osu!)$
    windowrulev2 = opaque,class:^(osu!)$,title:^(osu!)$
    windowrulev2 = noblur, class:^(bilibili)$,title:^(哔哩哔哩 (゜-゜)つロ 干杯~-bilibili)$
    windowrulev2 = opaque, class:^(bilibili)$
    windowrulev2 = opaque, class:^(class: org.jackhuang.hmcl.Launcher)$
    windowrulev2 = opaque, class:^(Minecraft 1.21.8)$
      